export const destinations = [
    {
        image:,
        h3:,
        subheader:,
        description:,
        buttonLink:
    },
    {
        image:,
        h3:,
        subheader:,
        description:,
        buttonLink:
    },
    {
        image:,
        h3:,
        subheader:,
        description:,
        buttonLink:
    },
]